 version: 0.0
 os: linux
 files:
   - source: ./
     destination: /var/www/html


 hooks:
   BeforeInstall:
      - location: script/install
        timeout: 300
        runas: root
      - location: script/start_server
        timeout: 300
        runas: root
    
